from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .suite_nodes import NODE_CLASS_MAPPINGS as SUITE_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as SUITE_NAMES
from .material_nodes import NODE_CLASS_MAPPINGS as MATERIAL_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as MATERIAL_NAMES
from .prompt_stages import NODE_CLASS_MAPPINGS as STAGE_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as STAGE_NAMES
from .unified import NODE_CLASS_MAPPINGS as UNIFIED_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as UNIFIED_NAMES
from .tipo_expansion import NODE_CLASS_MAPPINGS as EXPAND_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as EXPAND_NAMES

NODE_CLASS_MAPPINGS.update(SUITE_CLASSES)
NODE_DISPLAY_NAME_MAPPINGS.update(SUITE_NAMES)
NODE_CLASS_MAPPINGS.update(MATERIAL_CLASSES)
NODE_DISPLAY_NAME_MAPPINGS.update(MATERIAL_NAMES)
NODE_CLASS_MAPPINGS.update(STAGE_CLASSES)
NODE_DISPLAY_NAME_MAPPINGS.update(STAGE_NAMES)
NODE_CLASS_MAPPINGS.update(UNIFIED_CLASSES)
NODE_DISPLAY_NAME_MAPPINGS.update(UNIFIED_NAMES)
NODE_CLASS_MAPPINGS.update(EXPAND_CLASSES)
NODE_DISPLAY_NAME_MAPPINGS.update(EXPAND_NAMES)
WEB_DIRECTORY = "./web"

try:
    from server import PromptServer
except ImportError:
    pass
else:
    from .providers import register_routes
    register_routes()

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
